version: '3'
services:
  users:
    build:
      context: .
    ports:
      - 3000:3000
    command: npm run start
    volumes:
      - '.:/usr/src/app'
    networks:
      - curieXplore-paysage
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - curieXplore-paysage
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - curieXplore-paysage
networks:
  curieXplore-paysage:
volumes:
  mongodb: