version: '3'
services:
  curie-api:
    build:
      context: .
    ports:
      - 3000:3000
<<<<<<< HEAD
    command: npm run start:dev
    environment:
      - MONGO_URI='mongodb://mongo-curie:27017'
=======
    command: npm start
>>>>>>> 9f7a53e091278676186f7842a033ce6703397e31
    volumes:
      - './src:/app/src'
    networks:
      - curieXplore-paysage
    depends_on:
      - mongo-curie
  mongo-curie:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - curieXplore-paysage
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - curieXplore-paysage
    depends_on:
      - mongo-curie
networks:
  curieXplore-paysage:
volumes:
  mongodb:
