version: '3'
services:
  curie-api:
    build:
      context: .
    ports:
      - 3000:3000
    command: npm run start
    env_file: .env
    networks:
      - curieXplore-paysage
  mongo-curie:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - curieXplore-paysage
networks:
  curieXplore-paysage:
volumes:
  mongodb:
