version: '3'
services:
  users:
    build:
      context: .
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - '.:/usr/src/app'
    networks:
      - curieXplore-paysage
  mongo-curie:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - curieXplore-paysage
networks:
  curieXplore-paysage:
volumes:
  mongodb:
