version: '2'

services:
  cocoa-back:
    image : dataesr/cocoa-back:1.0
    #build: .
    networks:
      mongo_net:
    ports:
      - '3001:3001'
    links:
      - mongo
  
  mongo:
    image: mongo
    volumes:
    - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      mongo_net:
        ipv4_address: 172.16.0.1
    command: mongod --bind_ip 127.0.0.1,172.16.0.1


networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.254

volumes:
  data-volume: